name: Build Docker Image

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
      - 'develop'
    paths-ignore:
      - '.github/**'
      - '**.md'
    tags:
      - 'prod@*'

jobs:

  docker:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    outputs:
      environment: ${{ steps.prepare-build.outputs.environment }}
      shorthash: ${{ steps.prepare-build.outputs.short }}
    strategy:
      matrix:
        service: [nginx, php-fpm, php-cli]
        include:
          - service: nginx
            target: nginx
            dockerfile: nginx.Dockerfile
          - service: php-fpm
            target: fpm
            dockerfile: php.Dockerfile
          - service: php-cli
            target: cli
            dockerfile: php.Dockerfile

    steps:

      - name: Prepare build variables
        id: prepare-build
        run: |
            echo "::set-output name=short::${GITHUB_SHA:0:7}"
            if [[ "${{ github.ref_name }}" == "main" ]]; then
              echo "::set-output name=environment::prod"
            else
              echo "::set-output name=environment::dev"
            fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.1.0

      - name: Login to GitHub container registry
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # About the cache:
      # https://github.com/docker/build-push-action/blob/master/docs/advanced/cache.md#cache-backend-api
      - name: Build ${{ matrix.service }} Docker Image
        uses: docker/build-push-action@c84f38281176d4c9cdb1626ffafcd6b3911b5d94
        with:
          push: true
          build-args:
            "VERSION=${{ steps.prepare-build.outputs.environment }}-${{ steps.prepare-build.outputs.short }}"
          tags: ghcr.io/package-health/${{ matrix.service }}:${{ steps.prepare-build.outputs.environment }}-${{ steps.prepare-build.outputs.short }}
          file: ./docker/${{ matrix.dockerfile }}
          target: ${{ matrix.target }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  release-deploy:
    needs: docker
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Create release
      if: ${{ github.ref_type == 'tag' }}
      uses: softprops/action-gh-release@1e07f4398721186383de40550babbdf2b84acfc5
      with:
        name: "php.package.health ${{ needs.docker.outputs.environment }}-${{ needs.docker.outputs.shorthash }}"
        generate_release_notes: true

    - name: Send update to infrastructure repository
      if: ${{ github.ref_type == 'tag' || github.ref_name != 'main' }}
      uses: peter-evans/repository-dispatch@11ba7d3f32dc7cc919d1c43f1fec1c05260c26b5
      with:
        # personal access token with "repo" scope
        token: ${{ secrets.INFRA_REPO_ACCESS_TOKEN }}
        repository: package-health/infra-service
        event-type: deploy-new-version
        client-payload: '{"sha": "${{ github.sha }}", "environment": "${{ needs.docker.outputs.environment }}"}'
