name: Secret scan

on: [pull_request]

jobs:
  trufflehog:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        with:
          fetch-depth: 0

      - name: Scan code for hardcoded secrets
        uses: trufflesecurity/trufflehog@62ce9bac8bac135147aed681f93c96ca8c5adec7
        with:
          path: ./
          base: ${{ github.base_ref }}
          head: HEAD
