name: Secret scan

on: [pull_request]

jobs:
  trufflehog:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac
        with:
          fetch-depth: 0

      - name: Scan code for hardcoded secrets
        uses: trufflesecurity/trufflehog@f3257a44e0bcc689f58f6cf94d4b75ab7fae8ea0
        with:
          path: ./
          base: ${{ github.base_ref }}
          head: HEAD
