name: Secret scan

on: [pull_request]

jobs:
  trufflehog:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac
        with:
          fetch-depth: 0

      - name: Scan code for hardcoded secrets
        uses: trufflesecurity/trufflehog@39a603d2dc5d8c011e8ad54bffb9e12fb18fe2b4
        with:
          path: ./
          base: ${{ github.base_ref }}
          head: HEAD
