name: Secret scan

on: [pull_request]

jobs:
  trufflehog:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
        with:
          fetch-depth: 0

      - name: Scan code for hardcoded secrets
        uses: trufflesecurity/trufflehog@fd7e7e6e296c13ede7642002eb254ad8144ef736 # v3.70.1
        with:
          path: ./
          base: ${{ github.base_ref }}
          head: HEAD
