name: Secret scan

on: [pull_request]

jobs:
  trufflehog:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
        with:
          fetch-depth: 0

      - name: Scan code for hardcoded secrets
        uses: trufflesecurity/trufflehog@a7fc12240f8ce02df55c8b808755088f3b7eec7d
        with:
          path: ./
          base: ${{ github.base_ref }}
          head: HEAD
