name: Secret scan

on: [pull_request]

jobs:
  trufflehog:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
        with:
          fetch-depth: 0

      - name: Scan code for hardcoded secrets
        uses: trufflesecurity/trufflehog@800ac30ea0cad15f05be2062dcf2c8e3b43b4124
        with:
          path: ./
          base: ${{ github.base_ref }}
          head: HEAD
